import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Radio Ángel FM Reinos Unidos",
            artist: "RadioÁngelFM",
            cover: "https://img.freepik.com/vector-gratis/fondo-noticias-tecnologia-tierra-digital_1017-36675.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://edge.clrmedia.co.uk/angel_hb",
            active: true,
        },
        {
            name:"Capital Xtra",
            artist: "CapitalXtra",
            cover: "https://img.freepik.com/psd-gratis/maqueta-reproductor-multimedia-rose-gold-maqueta-reproductor-multimedia-rose-gold-3d_106244-1745.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://media-ice.musicradio.com/CapitalXTRALondonMP3",
            active: false,
        },
        {
            name:"More Radio",
            artist: "MoreRadio",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41311.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://s2.xrad.io:9596/stream/1/",
            active: false,
        },
        {
            name:"40 principales Mexico",
            artist: "40principales",
            cover: "https://img.freepik.com/vector-gratis/iconos-banderas_1010-531.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://26433.live.streamtheworld.com/LOS40_MEXICO_SC",
            active: false,
        },
        {
            name:"fm Globo",
            artist: "fmGlobo",
            cover: "https://img.freepik.com/psd-gratis/maqueta-reproductor-multimedia-rose-gold-maqueta-reproductor-multimedia-rose-gold-3d_106244-1745.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://15123.live.streamtheworld.com/XHPFFM_SC",
            active: false,
        },
        {
            name:"Stereo Joya",
            artist: "StereoJoya",
            cover: "https://cdn-icons-png.flaticon.com/512/1251/1251671.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://20323.live.streamtheworld.com/XEJP_FMAAC_SC",
            active: false,
        },
        {
            name:"101 FM Australia",
            artist: "101FM",
            cover: "https://img.freepik.com/vector-gratis/tierra-lineas-red_1017-8010.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://23203.live.streamtheworld.com/4CBLAAC_SC",
            active: false,
        },
        {
            name:"Hobart Fm",
            artist: "HobartFm",
            cover: "https://img.freepik.com/vector-gratis/fondo-onda-ecualizador-colorido_52683-33072.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://radio11.shoutcast.net.au/proxy/hobartfm?mp=/stream",
            active: false,
        },
        {
            name:"40 principales España",
            artist: "40principales",
            cover: "https://img.freepik.com/vector-gratis/grafico-tierra-3d-que-simboliza-ilustracion-comercio-mundial_456031-131.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://21263.live.streamtheworld.com/LOS40_SC",
            active: false,
         },
         {
            name:"Cadena Dial",
            artist: "CadenaDial",
            cover: "https://img.freepik.com/foto-gratis/dispositivo-digital-inalambrico-auriculares-rosa_53876-96804.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://21313.live.streamtheworld.com/CADENADIAL_SC",
            active: false,
         },
         {
            name:"La FM Colombia",
            artist: "LaFM",
            cover: "https://img.freepik.com/vector-gratis/grafico-tierra-3d-que-simboliza-ilustracion-comercio-mundial_456031-125.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://26583.live.streamtheworld.com/LA_FM_BOGAAC_SC",
            active: false,
         },
         {
            name:"Besame",
            artist: "Besame",
            cover: "https://img.freepik.com/vector-gratis/dia-mundial-radio-diseno-plano_23-2148802732.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://24483.live.streamtheworld.com/BESAME_MEDELLINAAC_SC",
            active: false,
         },
         {
            name:"Metropolitana Brasil",
            artist: "Metropolitana",
            cover: "https://img.freepik.com/vector-gratis/grafico-tierra-3d-que-simboliza-ilustracion-comercio-mundial_456031-125.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://f42.fabricahost.com.br/metropolitana985sp?f=1667844113N01GH9M30QHBAA8C7JNWGC89M37&tid=01GH9M30QHN0R1NXNQ1JW6RHV5",
            active: false,
         },
         {
            name:"93 FM",
            artist: "93FM",
            cover: "https://img.freepik.com/vector-gratis/fondo-musica_53876-90528.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://24083.live.streamtheworld.com/FM93_SC",
            active: false,
         },
         {
            name:"Skala Fm Denmark",
            artist: "SkalaFm",
            cover: "https://img.freepik.com/vector-gratis/fondo-noticias-tecnologia-tierra-digital_1017-36675.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://webradio.skala.fm/skala",
            active: false,
         },
         {
            name:"Radio Go Fm",
            artist: "RadioGoFm",
            cover: "https://img.freepik.com/psd-gratis/maqueta-microfono-escritorio-rectangular-vista-frontal_1332-10597.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://radioserver.dk/gofm",
            active: false,
         },
         {
            name:"Nostalgie Belgium",
            artist: "Nostalgie",
            cover: "https://img.freepik.com/vector-gratis/fondo-noticias-tecnologia-tierra-digital_1017-36675.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://25593.live.streamtheworld.com/NOSTALGIEWHATAFEELING_SC",
            active: false,
         },
         {
            name:"JOE",
            artist: "JOE",
            cover: "https://img.freepik.com/vector-gratis/concepto-marco-neon-aire_52683-52393.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://22673.live.streamtheworld.com/JOE_SC",
            active: false,
         },
         {
            name:"Rock And Pop Argentina",
            artist: "RockAndPop",
            cover: "https://img.freepik.com/vector-gratis/iconos-banderas_1010-531.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://24083.live.streamtheworld.com/ROCKANDPOP_SC",
            active: false,
         },
         {
            name:"Radio Vida Fm",
            artist: "RadioVidaFm",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41314.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://streaming450tb.locucionar.com/proxy/fmvida979?mp=/stream",
            active: false,
         },
         {
            name:"Skyrock FM France",
            artist: "SkyrockFM",
            cover: "https://img.freepik.com/vector-gratis/grafico-tierra-3d-que-simboliza-ilustracion-comercio-mundial_456031-131.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://icecast.skyrock.net/s/natio_mp3_128k?tvr_name=ecouterradioenligne&tvr_section1=128mp3",
            active: false,
         },
         {
            name:"Azur Fm",
            artist: "AzurFm",
            cover: "https://img.freepik.com/vector-gratis/texto-plano-dia-mundial-radio_23-2148825802.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://listen.radioking.com/radio/74176/stream/112165",
            active: false,
         },
         {
            name:"Black Beats Germany",
            artist: "Black Beats",
            cover: "https://img.freepik.com/vector-gratis/mapa-mundo-tecnologia-global-o-red-conexion-social-nodos-enlaces-ilustracion-vectorial_1284-1968.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://rautemusik-de-hz-fal-stream17.radiohost.de/blackbeats",
            active: false,
         },
         {
            name:"Kiss Fm",
            artist: "KissFm",
            cover: "https://img.freepik.com/psd-gratis/maqueta-reproductor-multimedia-rose-gold-maqueta-reproductor-multimedia-rose-gold-3d_106244-1745.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://topradio-stream32.radiohost.de/kissfm_mp3-192?ref=radiosonlinech&amsparams=radiosonlinech",
            active: false,
         },
         {
            name:"Besame Costa Rica",
            artist: "Besame",
            cover: "https://img.freepik.com/vector-gratis/grafico-tierra-3d-que-simboliza-ilustracion-comercio-mundial_456031-131.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://26593.live.streamtheworld.com/BESAME_CR_SC",
            active: false,
         },
         {
            name:"Columbia Stereo",
            artist: "ColumbiaStereo",
            cover: "https://img.freepik.com/vector-gratis/fondo-onda-ecualizador-colorido_52683-33072.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://streamer.radio.co/s3293a5a15/listen",
            active: false,
         },
         {
            name:"Italo Fm Holland",
            artist: "ItaloFm",
            cover: "https://img.freepik.com/vector-gratis/tierra-lineas-red_1017-8010.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://italo.italo.nu/fantasy",
            active: false,
         },
         {
            name:"Radio Star Maroc morocco",
            artist: "Radio Star Maroc",
            cover: "https://cdn-icons-png.flaticon.com/512/1251/1251671.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://manager8.streamradio.fr:1775/stream",
            active: false,
         },
         {
            name:"Radio Rfm Portugal",
            artist: "RadioRfm",
            cover: "https://img.freepik.com/psd-gratis/maqueta-reproductor-multimedia-rose-gold-maqueta-reproductor-multimedia-rose-gold-3d_106244-1745.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://20863.live.streamtheworld.com/RFM_SC",
            active: false,
         }, 
         {
            name:"Mega Hit",
            artist: "Mega Hit",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41311.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://25703.live.streamtheworld.com/MEGA_HITS_SC",
            active: false,
         }, 
         {
            name:"Fm Hit Uruguay ",
            artist: "FmHit ",
            cover: "https://img.freepik.com/psd-gratis/maqueta-microfono-escritorio-rectangular-vista-frontal_1332-10597.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://hit2.net.com.uy:8022/stream/1/",
            active: false,
         },
         {
            name:"Latina 92 Fm",
            artist: "Latina92Fm",
            cover: "https://img.freepik.com/vector-gratis/concepto-marco-neon-aire_52683-52393.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://fmlatina02.net.com.uy:8020/stream/1/",
            active: false,
         },
         {
            name:"JC Radio La Bruja Ecuador",
            artist: "JCRadioLaBruja",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41309.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://s7.yesstreaming.net:8040/stream",
            active: false,
         },
         {
            name:"Super Fm",
            artist: "SuperFm",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41314.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://dattavolt.com/8028/stream",
            active: false,
         },
         {
            name:"Reality Radio Canada",
            artist: "Reality Radio",
            cover: "https://img.freepik.com/vector-gratis/silueta-aparato-radio_23-2147501018.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://www.streamcontrol.net:8444/s/10080",
            active: false,
         },
         {
            name:"Hit 93 Toronto",
            artist: "Hit93Toronto",
            cover: "https://img.freepik.com/vector-gratis/radio-plana-retro-ilustrada_23-2148812864.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://listen.radioking.com/radio/75868/stream/113899",
            active: false,
         },
         {
            name:"VIPradio Dance US",
            artist: "VIPradioDance",
            cover: "https://img.freepik.com/vector-gratis/aire-letrero-neon-marco_23-2148818543.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://usa11.fastcast4u.com/proxy/vipdance?mp=/1",
            active: false,
         },
         {
            name:"Dash Radio",
            artist: "DashRadio",
            cover: "https://img.freepik.com/vector-gratis/fondo-musica_53876-90528.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ice55.securenetsystems.net/DASH62",
            active: false,
        },
    ];
}

export default chillHop;


